### ISSUE TITLE
Unable to process a review from p4v

### ISSUE THREAD

**Issue by Adrimeov** [p4paul/helix-docker#1]
Hi, I deployed you docker-compose on a Ubuntu machine. From my host machine I am not able to request a review from my p4v client. When I click on request a review; i received an Internal server error message. Here are the swarm logs (from the helix swarm container):

Let me know if you have an idea how to fix this.. 
#14 {main}
2020-05-14T16:05:01+00:00 INFO (6): Worker 1 startup.
2020-05-14T16:05:01+00:00 DEBUG (7): P4 (000000006f6164b8000000001e1065a7) start command: info
2020-05-14T16:05:01+00:00 DEBUG (7): P4 (000000006f6164b8000000001e1065a7) start command: help
2020-05-14T16:05:01+00:00 DEBUG (7): P4 (000000006f6164b8000000001e1065a7) start command: property -l -n P4.Swarm.URL
2020-05-14T16:05:01+00:00 DEBUG (7): P4 (000000006f6164b8000000001e1065a7) start command: property -a -n P4.Swarm.URL -v http://swarm.helix -s0
2020-05-14T16:05:01+00:00 DEBUG (7): P4 (000000006f6164b8000000001e1065a7) command failed: You don't have permission for this operation.
2020-05-14T16:05:01+00:00 ERR (3): P4\Connection\Exception\CommandException: Command failed: You don't have permission for this operation. in /opt/perforce/swarm/library/P4/Connection/AbstractConnection.php:1123
Stack trace:
#0 /opt/perforce/swarm/library/P4/Connection/AbstractConnection.php(809): P4\Connection\AbstractConnection->handleError(Object(P4\Connection\CommandResult))
#1 /opt/perforce/swarm/module/Application/src/Listener/WorkerListener.php(44): P4\Connection\AbstractConnection->run('property', Array)
#2 /opt/perforce/swarm/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Application\Listener\WorkerListener->setHostUrl(Object(Zend\EventManager\Event))
#3 /opt/perforce/swarm/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\EventManager\Event))
#4 /opt/perforce/swarm/module/Queue/src/Controller/IndexController.php(129): Zend\EventManager\EventManager->triggerEvent(Object(Zend\EventManager\Event))
#5 /opt/perforce/swarm/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Queue\Controller\IndexController->workerAction()
#6 /opt/perforce/swarm/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 /opt/perforce/swarm/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#8 /opt/perforce/swarm/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#9 /opt/perforce/swarm/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#10 /opt/perforce/swarm/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#11 /opt/perforce/swarm/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /opt/perforce/swarm/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#13 /opt/perforce/swarm/public/index.php(55): Zend\Mvc\Application->run()
#14 {main}
2020-05-14T16:05:35+00:00 DEBUG (7): P4 (000000006fade7c200000000378aa9ac) start command: Authenticating 172.18.0.1 for user jf
2020-05-14T16:05:35+00:00 DEBUG (7): P4 (000000006fade7c500000000378aa9ac) start command: login -s
2020-05-14T16:05:35+00:00 DEBUG (7): P4 (000000006fade7c500000000378aa9ac) start command: login -s
2020-05-14T16:05:35+00:00 DEBUG (7): P4 (000000006fade7c500000000378aa9ac) start command: login -s
2020-05-14T16:05:35+00:00 DEBUG (7): P4 (000000006fade7c500000000378aa9ac) start command: login -s
2020-05-14T16:05:35+00:00 DEBUG (7): P4 (000000006fade7c500000000378aa9ac) start command: login -s
2020-05-14T16:05:35+00:00 DEBUG (7): P4 (000000006fade7c500000000378aa9ac) start command: login -s
2020-05-14T16:05:35+00:00 DEBUG (7): P4 (0000000002d476df000000000dbd181a) start command: Authenticating 172.18.0.1 for user jf
2020-05-14T16:05:35+00:00 DEBUG (7): P4 (0000000002d476d8000000000dbd181a) start command: login -s
2020-05-14T16:05:35+00:00 DEBUG (7): P4 (0000000002d476d8000000000dbd181a) start command: login -s
2020-05-14T16:05:35+00:00 DEBUG (7): P4 (0000000002d476d8000000000dbd181a) start command: login -s
2020-05-14T16:05:35+00:00 DEBUG (7): P4 (0000000002d476d8000000000dbd181a) start command: login -s
2020-05-14T16:05:35+00:00 DEBUG (7): P4 (0000000002d476d8000000000dbd181a) start command: login -s
2020-05-14T16:05:35+00:00 DEBUG (7): P4 (0000000002d476d8000000000dbd181a) start command: login -s
2020-05-14T16:05:35+00:00 DEBUG (7): P4 (0000000002d476a2000000000dbd181a) start command: search (1301=64656661756C74 | 1301=37)
2020-05-14T16:05:35+00:00 DEBUG (7): P4 (0000000002d476d8000000000dbd181a) start command: protects -m
2020-05-14T16:05:40+00:00 DEBUG (7): P4 (0000000034165215000000005706b30b) start command: Authenticating 172.18.0.1 for user jf
2020-05-14T16:05:40+00:00 DEBUG (7): P4 (0000000034165214000000005706b30b) start command: login -s
2020-05-14T16:05:40+00:00 DEBUG (7): P4 (0000000034165214000000005706b30b) start command: login -s
2020-05-14T16:05:40+00:00 DEBUG (7): P4 (0000000034165214000000005706b30b) start command: login -s
2020-05-14T16:05:40+00:00 DEBUG (7): P4 (0000000034165214000000005706b30b) start command: login -s
2020-05-14T16:05:40+00:00 DEBUG (7): P4 (0000000034165214000000005706b30b) start command: login -s
2020-05-14T16:05:40+00:00 DEBUG (7): P4 (0000000034165214000000005706b30b) start command: login -s
2020-05-14T16:05:40+00:00 DEBUG (7): P4 (000000003416526e000000005706b30b) start command: info
2020-05-14T16:05:40+00:00 DEBUG (7): P4 (000000003416526e000000005706b30b) start command: property -l -n P4.Swarm.CommitURL
2020-05-14T16:05:40+00:00 DEBUG (7): P4 (000000003416526e000000005706b30b) start command: counters -u -e swarm-cache-*
2020-05-14T16:05:40+00:00 NOTICE (5): Review:addAction: Create a review for change [7], mode[]
2020-05-14T16:05:40+00:00 DEBUG (7): P4 (000000003416526e000000005706b30b) start command: counters -u -e swarm-review-fffffff8
2020-05-14T16:05:40+00:00 DEBUG (7): P4 (0000000034165214000000005706b30b) start command: info
2020-05-14T16:05:40+00:00 DEBUG (7): P4 (0000000034165214000000005706b30b) start command: change -Oo 7
2020-05-14T16:05:40+00:00 DEBUG (7): P4 (0000000034165214000000005706b30b) start command: spec -o change
2020-05-14T16:05:40+00:00 DEBUG (7): P4 (0000000034165214000000005706b30b) start command: describe -S 7
2020-05-14T16:05:40+00:00 DEBUG (7): P4 (000000003416526e000000005706b30b) start command: counter -u -i swarm-lock-6368616E67652D7265766965772D37
2020-05-14T16:05:40+00:00 DEBUG (7): P4 (000000003416526e000000005706b30b) command failed: You don't have permission for this operation.
2020-05-14T16:05:40+00:00 CRIT (2): P4\Connection\Exception\CommandException: Command failed: You don't have permission for this operation. in /opt/perforce/swarm/library/P4/Connection/AbstractConnection.php:1123
Stack trace:
#0 /opt/perforce/swarm/library/P4/Connection/AbstractConnection.php(809): P4\Connection\AbstractConnection->handleError(Object(P4\Connection\CommandResult))

**Comment by p4paul** [comment]
Hi, just so you are aware this is not an official Docker image or demonstration of Perforce, but something I created to demonstrate Docker to some of our developers.
Normally I use this with a 'seed' checkpoint so I have sample data, but it seems that when starting with an empty Perforce server I forgot to create a protection entry for the Swarm user.

You could do this manually:

    p4 -p4000 -usuper -Cutf8 protect

(login in with Passw0rd)

than add the line to the bottom of the protections (you must tab indent)

    super user swarm * //...

I'll see if I can fix the project.

Kind regards,
Paul

**Comment by p4paul** [comment]
There were a few other fixes needed to get the triggers working and set the P4.Swarm.URL to an external address.  I have pushed the changes.
To start from clean you will need to remove your `volumes/p4d-home` directory (any settings/changes to Perforce will be lost); then run a `docker-compose build` and `docker-compose up`.

**Comment by Adrimeov** [comment]
Thank you.
